<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-RafaelYuta/blob/main/atv2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Treino de NumPy — 42 exercícios hands-on

**Objetivo:** praticar manipulação de arrays NumPy (criação, slicing, broadcasting, álgebra linear, estatística, datas, strides).
**Regras:** use **apenas** NumPy (`import numpy as np`). Para reprodutibilidade, prefira `np.random.default_rng(seed)`.

In [2]:
import numpy as np

## Fáceis (24)

### 1. Vetor de zeros  _(fácil)_

Crie um array 1D com 10 zeros usando NumPy e mostre o dtype e o shape.

In [3]:
array = np.zeros(10)
print(array.dtype)
print(array.shape)

float64
(10,)


### 2. Vetor de uns  _(fácil)_

Crie um array 1D com 10 uns e transforme-o em float64.

In [4]:
array = np.ones(10)
np.float64

numpy.float64

### 3. Sequência 0–9  _(fácil)_

Crie um array com os inteiros de 0 a 9 (inclusive).

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 4. Matriz 3×3 com 0…8  _(fácil)_

Crie um array 3×3 com os valores 0…8 (reshape).


In [6]:
np.arange(9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 5. Índices não zero  _(fácil)_

Dado o vetor `v = np.array([1,2,0,0,4,0])`, encontre os índices dos elementos não nulos.


In [7]:
v = np.array([1,2,0,0,4,0])
z = []
for i in range(len(v)):
    if v[i] != 0:
      z.append(v[i])
print(z)


[np.int64(1), np.int64(2), np.int64(4)]


### 6. Linspace  _(fácil)_

Crie um vetor de 12 pontos igualmente espaçados no intervalo [0, 1].

In [8]:
np.linspace(0, 1, num=12)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

### 7. Identidade 5×5  _(fácil)_

Crie uma matriz identidade de ordem 5.

In [9]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 8. Aleatórios 3×3×3  _(fácil)_

Gere um array 3×3×3 com valores aleatórios uniformes em [0,1). Use `np.random.default_rng(42)`.

In [10]:
rng = np.random.default_rng(seed=42)
arr2 = rng.uniform(0, 1, (3, 3, 3))
print(arr2)

[[[0.77395605 0.43887844 0.85859792]
  [0.69736803 0.09417735 0.97562235]
  [0.7611397  0.78606431 0.12811363]]

 [[0.45038594 0.37079802 0.92676499]
  [0.64386512 0.82276161 0.4434142 ]
  [0.22723872 0.55458479 0.06381726]]

 [[0.82763117 0.6316644  0.75808774]
  [0.35452597 0.97069802 0.89312112]
  [0.7783835  0.19463871 0.466721  ]]]


### 9. Min/Max  _(fácil)_

Crie uma matriz 10×10 de aleatórios uniformes e mostre o valor mínimo e máximo.

In [11]:
array = rng.uniform(0, 1, (10, 10))
print(array)
print(array.min())
print(array.max())

[[0.04380377 0.15428949 0.68304895 0.74476216 0.96750973 0.32582536
  0.37045971 0.46955581 0.18947136 0.12992151]
 [0.47570493 0.22690935 0.66981399 0.43715192 0.8326782  0.7002651
  0.31236664 0.8322598  0.80476436 0.38747838]
 [0.2883281  0.6824955  0.13975248 0.1999082  0.00736227 0.78692438
  0.66485086 0.70516538 0.78072903 0.45891578]
 [0.5687412  0.139797   0.11453007 0.66840296 0.47109621 0.56523611
  0.76499886 0.63471832 0.5535794  0.55920716]
 [0.3039501  0.03081783 0.43671739 0.21458467 0.40852864 0.85340307
  0.23393949 0.05830274 0.28138389 0.29359376]
 [0.66191651 0.55703215 0.78389821 0.66431354 0.40638686 0.81402038
  0.16697292 0.02271207 0.09004786 0.72235935]
 [0.46187723 0.16127178 0.50104478 0.1523121  0.69632038 0.44615628
  0.38102123 0.30151209 0.63028259 0.36181261]
 [0.08764992 0.1180059  0.96189766 0.90858069 0.69970713 0.26586996
  0.96917638 0.7787509  0.71689019 0.4493615 ]
 [0.27224156 0.09639096 0.9026024  0.45577629 0.20236336 0.30595662
  0.57921957 

### 10. Padronização 1D  _(fácil)_

Dado `x = [1,2,3,4,5]`, crie um array float e normalize para média 0 e desvio 1.

In [12]:
x = np.array([1, 2, 3, 4, 5], dtype=float)
x_norm = (x - x.mean()) / x.std()
print(x_norm)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


### 11. Conversão de tipos  _(fácil)_

Converta `np.array([1,2,3])` (int32) para float32 e depois para int64.

In [13]:
np.array([1,2,3])
np.int32
np.float64

numpy.float64

### 12. Clipping  _(fácil)_

Dado `a = [2, 5, 7, 1, 9]`, limite os valores ao intervalo [0,5] (valores acima de 5 tornam-se 5).

In [14]:
a = [2, 5, 7, 1, 9]
np.clip(a, 0, 5)

array([2, 5, 5, 1, 5])

### 13. Inversão  _(fácil)_

Crie um vetor de 0 a 9 e inverta a ordem (sem usar `[::-1]`).

In [15]:
array = np.arange(10)
array = np.flip(array)
print(array)

[9 8 7 6 5 4 3 2 1 0]


### 14. Empilhamento  _(fácil)_

Dado `a = [1,2,3]` e `b = [4,5,6]`, empilhe horizontal e verticalmente.

In [16]:
a = [1,2,3]
b = [4,5,6]
array = np.stack((a, b))
print(array)
array = np.stack((a, b), axis=-1)
print(array)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


### 15. Diagonal  _(fácil)_

Crie uma matriz 4×4 com a diagonal principal igual a 5 e as demais entradas zero.

In [17]:
m = np.diag([5, 5, 5, 5])

print(m)

[[5 0 0 0]
 [0 5 0 0]
 [0 0 5 0]
 [0 0 0 5]]


### 16. Somas por eixo  _(fácil)_

Para a matriz `A = np.arange(12).reshape(3,4)`, calcule a soma por linhas e por colunas.

In [18]:
A = np.arange(12).reshape(3, 4)

soma_linhas = A.sum(axis=1)
soma_colunas = A.sum(axis=0)

print("Soma por linhas:", soma_linhas)
print("Soma por colunas:", soma_colunas)

Soma por linhas: [ 6 22 38]
Soma por colunas: [12 15 18 21]


### 17. Frequências inteiras  _(fácil)_

Gere 100 inteiros aleatórios em [0,9] e conte as frequências de cada valor (0 a 9).

In [19]:
x = np.random.randint(0, 10, 100)
freq = np.bincount(x, minlength=10)
print("Frequências 0 a 9:", freq)

Frequências 0 a 9: [ 9  9 11  9  6  4 14 10 13 15]


### 18. Slicing com passo  _(fácil)_

Dado `v = np.arange(20)`, selecione cada 3º elemento começando do índice 1.

In [20]:
v = np.arange(20)
res = v[1::3]
print(res)

[ 1  4  7 10 13 16 19]


### 19. Máscara booleana  _(fácil)_

Crie uma máscara para números pares de `0…19` e use-a para filtrar o vetor.

In [21]:
v = np.arange(20)
mask = (v % 2 == 0)
pares = v[mask]
print("Máscara =", mask)

Máscara = [ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False]


### 20. Lista de listas → array  _(fácil)_

Converta `[[1,2,3],[4,5,6]]` em `ndarray`, verifique `shape` e `dtype`.

In [22]:
lista = [[1, 2, 3], [4, 5, 6]]
A = np.array(lista)
print("Shape:", A.shape)
print("Dtype:", A.dtype)

Shape: (2, 3)
Dtype: int64


### 21. Datas básicas  _(fácil)_

Crie um array de datas diárias de 2025-01-01 a 2025-01-07 (inclusive).

In [23]:
datas = np.arange('2025-01-01', '2025-01-08', dtype='datetime64[D]')
print(datas)

['2025-01-01' '2025-01-02' '2025-01-03' '2025-01-04' '2025-01-05'
 '2025-01-06' '2025-01-07']


### 22. Centralizar colunas  _(fácil)_

Dada `A = np.array([[1.,2.,3.],[4.,5.,6.]])`, subtraia a média de cada coluna.

In [24]:
A = np.array([[1., 2., 3.],[4., 5., 6.]])
media_colunas = A.mean(axis=0)
A_centralizada = A - media_colunas
print("Média por coluna:", media_colunas)
print("Matriz centralizada:\n", A_centralizada)

Média por coluna: [2.5 3.5 4.5]
Matriz centralizada:
 [[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]


### 23. Produto elemento-a-elemento vs. escalar  _(fácil)_

Dadas `a=[1,2,3]` e `b=[4,5,6]`, calcule produto elemento a elemento e o produto escalar.

In [25]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
elemento = a * b
escalar = np.dot(a, b)

print("elemento", elemento)
print("escalar:", escalar)

elemento [ 4 10 18]
escalar: 32


### 24. Troca de colunas  _(fácil)_

Troque as colunas 0 e 2 de `A = np.arange(12).reshape(3,4)` sem copiar (sempre que possível).


In [26]:
A = np.arange(12).reshape(3, 4)
print("Antes:\n", A)
A[:, [0, 2]] = A[:, [2, 0]]
print("Depois:\n", A)

Antes:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Depois:
 [[ 2  1  0  3]
 [ 6  5  4  7]
 [10  9  8 11]]


### 25. Flatten vs. ravel  _(médio)_

Mostre a diferença entre `flatten()` (cópia) e `ravel()` (view quando possível). Modifique o resultado de `ravel()` e observe o original.

In [27]:
A = np.array([[1, 2], [3, 4]])
print("original:\n", A)

f = A.flatten()
r = A.ravel()

r[0] = 99

print("original:\n", A)
print("ravel:", r)
print("flatten:", f)

original:
 [[1 2]
 [3 4]]
original:
 [[99  2]
 [ 3  4]]
ravel: [99  2  3  4]
flatten: [1 2 3 4]


### 26. Tabuleiro 8×8  _(médio)_

Crie uma matriz 8×8 com padrão de tabuleiro (0 e 1 alternados).

In [28]:
tabuleiro = np.zeros((8, 8), dtype=int)
tabuleiro[1::2, ::2] = 1
tabuleiro[::2, 1::2] = 1

print(tabuleiro)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 27. np.where condicional  _(médio)_

Dado `x = np.arange(-5,6)`, substitua negativos por 0 e mantenha não-negativos.

In [29]:
x = np.arange(-5, 6)
print(x)
y = np.where(x < 0, 0, x)
print(y)

[-5 -4 -3 -2 -1  0  1  2  3  4  5]
[0 0 0 0 0 0 1 2 3 4 5]


### 28. Precisão de média  _(médio)_

Gere 1_000_000 floats uniformes em [0,1) e compute a média. Compare com o valor teórico 0.5 (erro absoluto).


In [30]:
x = np.random.rand(1_000_000)
media = x.mean()
erro = abs(media - 0.5)
print(f"Média amostral: {media:.6f}")
print(f"Erro absoluto:  {erro:.6f}")

Média amostral: 0.499973
Erro absoluto:  0.000027


### 29. Produto cartesiano (broadcasting)  _(médio)_

Dado `a=[1,2,3]` e `b=[10,20,30,40]`, gere todas as somas possíveis `a_i + b_j` via broadcasting (matriz 3×4).

In [31]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30, 40])
somas = a[:, None] + b
print(somas)

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


### 30. Convolução 1D simples  _(médio)_

Implemente uma convolução 1D 'valid' de um sinal `s` por um kernel `k` usando `np.flip` e `np.lib.stride_tricks.sliding_window_view` (sem `np.convolve`).

In [32]:
s = np.array([1, 2, 3, 4, 5, 6, 7])
k = np.array([1, 2, 1])

flip = np.flip(k)
windows = np.lib.stride_tricks.sliding_window_view(s, window_shape=len(k))
convolucao = np.sum(windows * flip, axis=1)

print(s)
print(k)
print(convolucao)

[1 2 3 4 5 6 7]
[1 2 1]
[ 8 12 16 20 24]


### 31. Normalização min–max por coluna  _(médio)_

Dada `A = rng.normal(size=(5,4))`, normalize cada coluna para o intervalo [0,1], tratando colunas constantes.

In [33]:
A = rng.normal(size=(5, 4))
print(A)

normal = np.copy(A)
valorMin = normal.min(axis=0)
valorMax = normal.max(axis=0)
dif = valorMax - valorMin
dif[dif == 0] = 1.0

normal = (normal - valorMin) / dif
print()
print(normal)

[[ 0.35687106  1.46330289 -1.18876305 -0.63975153]
 [-0.92657594 -0.3898098  -1.37668615  0.63515095]
 [-0.2222227  -1.47080629 -1.01557908  0.31351385]
 [ 0.83812657  1.99673089  2.91386247  0.41440943]
 [-0.98953812 -2.13204628  0.26771146 -0.8129411 ]]

[[0.73668282 0.87080242 0.04379932 0.11959845]
 [0.03444952 0.42197397 0.         1.        ]
 [0.41983381 0.16015395 0.08416338 0.77788905]
 [1.         1.         1.         0.84756389]
 [0.         0.         0.38326045 0.        ]]


### 32. Ordenar por coluna  _(médio)_

Ordene as linhas de `A = np.array([[3,9],[1,4],[2,5]])` pelo valor crescente da 2ª coluna.


In [34]:
A = np.array([[3, 9], [1, 4], [2, 5]])
print(A)
print()
ordenado = A[A[:, 1].argsort()]
print(ordenado)

[[3 9]
 [1 4]
 [2 5]]

[[1 4]
 [2 5]
 [3 9]]


### 33. Únicos + contagens + primeira ocorrência  _(médio)_

Para `x = [3,1,2,3,2,3,1]`, obtenha valores únicos, contagens e índice da primeira ocorrência de cada valor.

In [35]:
x = np.array([3, 1, 2, 3, 2, 3, 1])

unicos, contagens = np.unique(x, return_counts=True)
print(unicos)
print(contagens)

[1 2 3]
[2 2 3]


### 34. Matriz de distâncias 2D  _(médio)_

Dada `P` com N pontos 2D, compute a matriz NxN de distâncias euclidianas sem loops explícitos.

In [36]:
rng = np.random.default_rng(seed=42)
P = rng.random((5, 2))
print(P)

dif = P[:, np.newaxis, :] - P[np.newaxis, :, :]
resultado = np.sqrt(np.sum(dif**2, axis=-1))
print()
print(resultado)

[[0.77395605 0.43887844]
 [0.85859792 0.69736803]
 [0.09417735 0.97562235]
 [0.7611397  0.78606431]
 [0.12811363 0.45038594]]

[[0.         0.2719947  0.86613689 0.34742234 0.64594493]
 [0.2719947  0.         0.81348895 0.13177683 0.77110793]
 [0.86613689 0.81348895 0.         0.69337655 0.52633161]
 [0.34742234 0.13177683 0.69337655 0.         0.71652074]
 [0.64594493 0.77110793 0.52633161 0.71652074 0.        ]]


### 35. Covariância e correlação  _(médio)_

Simule uma matriz 1000×3 de N(0,1) e compute `cov` (colunas como variáveis) e `corrcoef`.

In [37]:
rng = np.random.default_rng(0)
X = rng.standard_normal((1000, 3))
cov = np.cov(X, rowvar=False)
corr = np.corrcoef(X, rowvar=False)

print(cov)
print()
print(corr)

[[ 0.98258675 -0.01023134 -0.0078957 ]
 [-0.01023134  0.93283837 -0.0171007 ]
 [-0.0078957  -0.0171007   1.04397623]]

[[ 1.         -0.01068671 -0.00779578]
 [-0.01068671  1.         -0.01732867]
 [-0.00779578 -0.01732867  1.        ]]


### 36. One-hot encoding  _(médio)_

Converta os rótulos `y = [2,0,1,2]` em codificação one-hot usando apenas operações NumPy.

In [38]:
y = np.array([2, 0, 1, 2])
classes = y.max() + 1
x = np.eye(classes)[y]

print(x)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 37. k-means 2D (NumPy puro)  _(difícil)_

Implemente k-means com K=3 em pontos 2D: inicialize centróides aleatórios, faça 10 iterações de (1) atribuir pontos ao centróide mais próximo e (2) recomputar centróides.

In [39]:
rng = np.random.default_rng(seed=42)
pontos = rng.random((100, 2))
K = 3
iteracoes = 10

indices_iniciais = rng.choice(pontos.shape[0], K, replace=False)
centroides = pontos[indices_iniciais]

print("Pontos originais:\n", pontos)
print("\nCentróides iniciais:\n", centroides)

for i in range(iteracoes):
    distancias = np.sqrt(((pontos[:, np.newaxis, :] - centroides[np.newaxis, :, :])**2).sum(axis=2))
    rotulos = np.argmin(distancias, axis=1)

    novos_centroides = np.array([pontos[rotulos == k].mean(axis=0) for k in range(K)])
    centroides = novos_centroides

print("\nCentróides finais após", iteracoes, "iterações:\n", centroides)
print("\nRótulos dos pontos:\n", rotulos)

Pontos originais:
 [[0.77395605 0.43887844]
 [0.85859792 0.69736803]
 [0.09417735 0.97562235]
 [0.7611397  0.78606431]
 [0.12811363 0.45038594]
 [0.37079802 0.92676499]
 [0.64386512 0.82276161]
 [0.4434142  0.22723872]
 [0.55458479 0.06381726]
 [0.82763117 0.6316644 ]
 [0.75808774 0.35452597]
 [0.97069802 0.89312112]
 [0.7783835  0.19463871]
 [0.466721   0.04380377]
 [0.15428949 0.68304895]
 [0.74476216 0.96750973]
 [0.32582536 0.37045971]
 [0.46955581 0.18947136]
 [0.12992151 0.47570493]
 [0.22690935 0.66981399]
 [0.43715192 0.8326782 ]
 [0.7002651  0.31236664]
 [0.8322598  0.80476436]
 [0.38747838 0.2883281 ]
 [0.6824955  0.13975248]
 [0.1999082  0.00736227]
 [0.78692438 0.66485086]
 [0.70516538 0.78072903]
 [0.45891578 0.5687412 ]
 [0.139797   0.11453007]
 [0.66840296 0.47109621]
 [0.56523611 0.76499886]
 [0.63471832 0.5535794 ]
 [0.55920716 0.3039501 ]
 [0.03081783 0.43671739]
 [0.21458467 0.40852864]
 [0.85340307 0.23393949]
 [0.05830274 0.28138389]
 [0.29359376 0.66191651]
 [0.55

### 38. PCA básica (autovetores)  _(difícil)_

Implemente PCA 2D→1D: centralize `X` (N×2), calcule covariância, autovetores, projete em 1D e reconstrua aproximado.

In [40]:
rng = np.random.default_rng(seed=0)
dados = rng.multivariate_normal([0, 0], [[1, 0.5], [0.5, 1]], 100)

print("Shape dos dados originais:", dados.shape)
dados_centralizados = dados - dados.mean(axis=0)
matriz_covariancia = np.cov(dados_centralizados, rowvar=False)
print("\nMatriz de covariância:\n", matriz_covariancia)
autovalores, autovetores = np.linalg.eig(matriz_covariancia)
print("\nAutovalores:", autovalores)
print("Autovetores:\n", autovetores)
indice_componente_principal = np.argmax(autovalores)
componente_principal = autovetores[:, indice_componente_principal]
dados_projetados = dados_centralizados @ componente_principal.reshape(-1, 1)
print("\nShape dos dados projetados:", dados_projetados.shape)
dados_reconstruidos = dados_projetados @ componente_principal.reshape(1, -1) + dados.mean(axis=0)
print("Shape dos dados reconstruídos:", dados_reconstruidos.shape)

Shape dos dados originais: (100, 2)

Matriz de covariância:
 [[1.04867797 0.48708999]
 [0.48708999 0.82698627]]

Autovalores: [1.43737538 0.43828887]
Autovetores:
 [[ 0.78163111 -0.62374097]
 [ 0.62374097  0.78163111]]

Shape dos dados projetados: (100, 1)
Shape dos dados reconstruídos: (100, 2)


### 39. Convolução 2D (im2col)  _(difícil)_

Implemente convolução 2D 'valid' de uma imagem `I` por um kernel `K` usando `sliding_window_view` para gerar blocos e multiplicação matricial.

In [41]:
I = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

K = np.array([[1, 0],
              [0, 1]])

print("Imagem I:\n", I)
print("\nKernel K:\n", K)

altura_I, largura_I = I.shape
altura_K, largura_K = K.shape

altura_saida = altura_I - altura_K + 1
largura_saida = largura_I - largura_K + 1

blocos = np.lib.stride_tricks.sliding_window_view(I, window_shape=K.shape)

print("\nBlocos (sliding_window_view):\n", blocos)

blocos_reshape = blocos.reshape(-1, altura_K * largura_K)

print("\nBlocos remodelados:\n", blocos_reshape)

kernel_reshape = K.reshape(-1, 1)

print("\nKernel remodelado:\n", kernel_reshape)

convolucao_valid = blocos_reshape @ kernel_reshape

convolucao_valid = convolucao_valid.reshape(altura_saida, largura_saida)

print("\nResultado da Convolução 2D (Valid):\n", convolucao_valid)

Imagem I:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Kernel K:
 [[1 0]
 [0 1]]

Blocos (sliding_window_view):
 [[[[ 1  2]
   [ 5  6]]

  [[ 2  3]
   [ 6  7]]

  [[ 3  4]
   [ 7  8]]]


 [[[ 5  6]
   [ 9 10]]

  [[ 6  7]
   [10 11]]

  [[ 7  8]
   [11 12]]]


 [[[ 9 10]
   [13 14]]

  [[10 11]
   [14 15]]

  [[11 12]
   [15 16]]]]

Blocos remodelados:
 [[ 1  2  5  6]
 [ 2  3  6  7]
 [ 3  4  7  8]
 [ 5  6  9 10]
 [ 6  7 10 11]
 [ 7  8 11 12]
 [ 9 10 13 14]
 [10 11 14 15]
 [11 12 15 16]]

Kernel remodelado:
 [[1]
 [0]
 [0]
 [1]]

Resultado da Convolução 2D (Valid):
 [[ 7  9 11]
 [15 17 19]
 [23 25 27]]


### 40. Sistemas lineares e resíduo  _(difícil)_

Gere uma matriz A (100×100) bem-condicionada, um vetor b e resolva `Ax=b` com `np.linalg.solve`. Compute o resíduo relativo `||Ax−b||/||b||` e `cond(A)`.

In [42]:
rng = np.random.default_rng(seed=42)
n = 100
A = rng.random((n, n)) + np.diag(np.full(n, 10))
b = rng.random(n)

x = np.linalg.solve(A, b)

residual = A @ x - b

residualRelativo = np.linalg.norm(residual) / np.linalg.norm(b)

numeroCondicional = np.linalg.cond(A)

print("Relative Residual:", residualRelativo)
print("Condition Number:", numeroCondicional)

Relative Residual: 3.3341961692899425e-16
Condition Number: 9.036195384048026


### 41. Regressão linear (OLS) com NumPy  _(difícil)_

Dado `X` (N×d) e `y`, calcule os coeficientes OLS usando `np.linalg.lstsq` e avalie RMSE no treino.

In [43]:
rng = np.random.default_rng(seed=42)
N, d = 100, 2
X = rng.random((N, d))
X = np.hstack([np.ones((N, 1)), X])
coeficientes_verdadeiros = np.array([1.5, 2.0, -1.0])
y = X @ coeficientes_verdadeiros + rng.normal(0, 0.5, N)

coeficientes, residuos, rank, s = np.linalg.lstsq(X, y, rcond=None)

print("Coeficientes verdadeiros:", coeficientes_verdadeiros)
print("Coeficientes estimados (OLS):", coeficientes)

y_pred = X @ coeficientes
rmse = np.sqrt(((y - y_pred)**2).mean())

print("\nRMSE nos dados de treino:", rmse)

Coeficientes verdadeiros: [ 1.5  2.  -1. ]
Coeficientes estimados (OLS): [ 1.34913958  2.02592087 -0.77701356]

RMSE nos dados de treino: 0.49895196706211464


### 42. Rolling window 2D com strides  _(difícil)_

Usando `sliding_window_view`, compute a média local 3×3 de uma imagem 2D sem laços explícitos.

In [45]:
image = np.arange(25).reshape(5, 5)
print(image)

windows = np.lib.stride_tricks.sliding_window_view(image, window_shape=(3, 3))

mean_image = windows.mean(axis=(-2, -1))

print(mean_image)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 6.  7.  8.]
 [11. 12. 13.]
 [16. 17. 18.]]
